language: php

php:
  # - 7.2
  # - 7.3
  # - 7.4
  - 8.1
  - 8.2

sudo: false

addons:
  # postgresql: "9.4"
  # mysql: "5.6"
  postgresql: "12.0"
  mysql: "8.1"

services:
  - postgresql
  - mysql

env:
  global:
    - DEFAULT=1
  matrix:
    - TESTDB=mysql
    - TESTDB=postgresql

matrix:
  fast_finish: true
  include:
    # - php: 7.2
    - php: 8.1

install:
  - composer self-update
  - composer install --dev

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - cp tests/createdb.sh.${TESTDB} tests/createdb.sh
  - sh tests/createdb.sh
  - export TESTDB=${TESTDB}

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit tests/TestCase/Model/Table/MembersTableTest.php --stderr; fi"

notifications:
  email: false
